services:
  - type: web
    name: recruitment-dashboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:application"
    healthCheckPath: "/health"
    envVars:
      - key: PYTHONPATH
        value: "."
      - key: APP_HOST
        value: "0.0.0.0"
      - key: APP_DEBUG
        value: "False" 